os: linux
branches:
  only:
    - master
language: node_js
node_js:
  - 14

git:
  depth: 3
  quiet: true
  submodules: false

cache:
  directories:
    - vuejs/.yarn/cache
    - vuejs/node_modules

install: bash ./scripts/install.sh

script: bash ./scripts/build.sh

deploy:
  - provider: script
    skip_cleanup: true
    script: bash ./scripts/deploy.sh
    on:
      branch: master

after_deploy: bash ./scripts/after-deploy.sh
